name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ../..
      - name: Install videoparquet (editable)
        run: |
          pip install -e .
        working-directory: ../..
      - name: Install pytest
        run: |
          pip install pytest
        working-directory: ../..
      - name: Install ffmpeg (brew)
        run: |
          brew install ffmpeg
      - name: Run tests
        run: |
          pytest tests/
        working-directory: ../..

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine
        working-directory: ../..
      - name: Build package
        run: |
          python -m build
        working-directory: ../..
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true 
