name: Test videoparquet

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install videoparquet (editable)
        run: |
          pip install -e .
      - name: Install pytest
        run: |
          pip install pytest
      - name: Install ffmpeg (brew)
        run: |
          brew uninstall --ignore-dependencies ffmpeg || true
          curl -L -o ffmpeg.7z https://evermeet.cx/ffmpeg/ffmpeg-120002-gb1172b8cc6.7z
          7z x ffmpeg.7z
          chmod +x ffmpeg ffprobe
          sudo mv ffmpeg /usr/local/bin/ffmpeg
          sudo mv ffprobe /usr/local/bin/ffprobe
          ffmpeg -version
          ffmpeg -h encoder=ffv1 | grep gbrp
      - name: Run tests
        run: |
          pytest tests/

  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install videoparquet (editable)
        run: |
          pip install -e .
      - name: Install pytest
        run: |
          pip install pytest
      - name: Download and install static ffmpeg (johnvansickle)
        run: |
          wget -O ffmpeg-release-amd64-static.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          tar -xf ffmpeg-release-amd64-static.tar.xz
          cd ffmpeg-*-amd64-static
          sudo cp ffmpeg ffprobe /usr/local/bin/
          ffmpeg -version
          ffmpeg -h encoder=ffv1 | grep gbrp
      - name: Run tests
        run: |
          pytest tests/ 
